### ISSUE TITLE
Exposed mongodb+srv credentials

### ISSUE THREAD

**Issue by eth0izzle** [melquisedecfelipe/tindev#2]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@cluster0-nejwy.mongodb.net` in file [/backend/src/server.js](https://github.com/melquisedecfelipe/tindev/blob/master/backend/src/server.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by melquisedecfelipe** [comment]
Update server, thanks man
